# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
        migrations.AddField(
            model_name='songs',
            name='file_type',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='song_title',
            field=models.CharField(default=250, max_length=250),
            preserve_default=False,
        ),
    ]
