# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-05 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170501_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default=1000, max_length=1000),
            preserve_default=False,
        ),
    ]
